"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, Eye, EyeOff, LockKeyhole, LoaderCircle } from "lucide-react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { api, Notice } from "./shared";

export function AdminAuth({ mode = "login" }: { mode?: "login" | "forgot" | "reset" }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [showPassword, setShowPassword] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (busy) return; setBusy(true); setError(""); setSuccess(""); const data = new FormData(event.currentTarget); const email = String(data.get("email") || "").trim(); const password = String(data.get("password") || ""); try { const client = getSupabaseBrowserClient(); if (!client) throw new Error("Admin access has not been configured. Contact the site owner.");
      if (mode === "forgot") { const { error } = await client.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/auth/callback?next=/admin/reset-password` }); if (error) throw new Error("Unable to send recovery instructions. Please try again later."); setSuccess("If this address can receive account recovery emails, instructions will arrive shortly."); }
      else if (mode === "reset") { if (password.length < 12) throw new Error("Use a password with at least 12 characters."); if (password !== String(data.get("confirm"))) throw new Error("The passwords do not match."); const { data: user, error: userError } = await client.auth.getUser(); if (userError || !user.user) throw new Error("This recovery link has expired. Request a new link."); const { error } = await client.auth.updateUser({ password }); if (error) throw new Error("Unable to update your password. Please request a fresh recovery link."); await client.auth.signOut(); router.replace("/admin/login?password=updated"); router.refresh(); }
      else { const { error } = await client.auth.signInWithPassword({ email, password }); if (error) throw new Error("Unable to sign in. Check your credentials and try again."); try { await api("/api/admin/session"); } catch { await client.auth.signOut(); router.replace("/admin/denied"); return; } router.replace("/admin"); router.refresh(); }
    } catch (e) { setError(e instanceof Error ? e.message : "Unable to complete this request. Please try again."); } finally { setBusy(false); } }
  return <div className="ad-auth"><header><Link href="/"><img src="/assets-1/logo.png" alt="Surprisewala" /></Link><Link href="/">Back to website <ArrowRight size={15} /></Link></header><main className="ad-auth-main"><div className="ad-auth-intro"><span className="ad-eyebrow">Surprisewala workspace</span><h1>Behind every<br /><em>beautiful surprise.</em></h1><p>A focused workspace for the people who make unforgettable moments happen.</p><div className="ad-auth-mark"><LockKeyhole size={18} /><span>Secure team access</span></div></div><section className="ad-auth-card"><span className="ad-eyebrow">Team access</span><h2>{mode === "forgot" ? "Reset your password" : mode === "reset" ? "Choose a new password" : "Welcome back"}</h2><p>{mode === "forgot" ? "Enter your email to request secure recovery instructions." : mode === "reset" ? "Use a strong, unique password for your account." : "Sign in to manage your Surprisewala business."}</p><form onSubmit={submit}>
      {mode !== "reset" && <label className="ad-field">Email address<input name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@example.com" /></label>}
      {mode !== "forgot" && <label className="ad-field">{mode === "reset" ? "New password" : "Password"}<span className="ad-password"><input name="password" type={showPassword ? "text" : "password"} autoComplete={mode === "reset" ? "new-password" : "current-password"} required minLength={mode === "reset" ? 12 : 1} maxLength={128} /><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword(v => !v)}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></span></label>}
      {mode === "reset" && <label className="ad-field">Confirm password<input name="confirm" type="password" autoComplete="new-password" required minLength={12} maxLength={128} /></label>}
      {mode === "login" && <Link className="ad-forgot-link" href="/admin/forgot-password">Forgot password?</Link>}<Notice error={error} success={success} /><button className="ad-button" type="submit" disabled={busy}>{busy ? <LoaderCircle size={17} className="ad-spin" /> : <ArrowRight size={17} />}{busy ? "Please wait…" : mode === "forgot" ? "Send recovery instructions" : mode === "reset" ? "Update password" : "Sign in"}</button></form>{mode !== "login" && <Link className="ad-auth-back" href="/admin/login">Back to sign in</Link>}<div className="ad-auth-footnote">Access is available to approved team members.</div></section></main><footer>Surprisewala · Business console</footer></div>;
}
