"use client";

import Link from "next/link";
import { ArrowUpRight, CalendarClock, Gift, UsersRound, CalendarCheck2, ShoppingBag, Layers3, Images, Star, Clock3 } from "lucide-react";
import { Badge, date, Empty, Loading, money, Notice, Row, str, useResource, Retry } from "./shared";

type Overview = { metrics: Record<string, number>; recentOrders: Row[]; upcoming: Row[]; recentCustomers: Row[]; recentActivity: Row[] };
const metricCards = [
  { key: "totalOrders", label: "Total orders", icon: ShoppingBag, href: "/admin/orders" }, { key: "newOrders", label: "New orders", icon: Clock3, href: "/admin/orders?status=new" }, { key: "confirmedOrders", label: "Confirmed", icon: CalendarCheck2, href: "/admin/orders?status=confirmed" }, { key: "upcomingSurprises", label: "Upcoming surprises", icon: CalendarClock, href: "/admin/orders?upcoming=upcoming" }, { key: "completedOrders", label: "Completed", icon: CalendarCheck2, href: "/admin/orders?status=completed" }, { key: "totalCustomers", label: "Customers", icon: UsersRound, href: "/admin/customers" }, { key: "activePackages", label: "Active packages", icon: Gift, href: "/admin/packages?status=active" }, { key: "collections", label: "Collections", icon: Layers3, href: "/admin/collections" }, { key: "publishedReviews", label: "Published reviews", icon: Star, href: "/admin/reviews?status=published" }, { key: "galleryItems", label: "Gallery items", icon: Images, href: "/admin/gallery" },
];
export function AdminDashboard({ role }: { role: string }) {
  const { data, error, loading, refresh } = useResource<Overview>("/api/admin/overview"); const editor = role === "editor";
  return <><div className="ad-page-heading"><div><span className="ad-eyebrow">Your workspace at a glance</span><h1>Make every moment count.</h1><p>{editor ? "Keep your packages, collections, and customer stories up to date." : "A clear view of your business and the surprises coming next."}</p></div>{!editor && <Link className="ad-button" href="/admin/orders?upcoming=upcoming"><CalendarClock size={17} />Upcoming surprises</Link>}</div><Notice error={error} />{error && <Retry onClick={refresh} />}{loading ? <Loading /> : data && <><div className="ad-metric-grid">{metricCards.filter(metric => !editor || ["activePackages", "collections", "publishedReviews", "galleryItems"].includes(metric.key)).map(metric => <Link className="ad-metric" href={metric.href} key={metric.key}><div><span>{metric.label}</span><metric.icon size={18} /></div><strong>{(data.metrics[metric.key] ?? 0).toLocaleString()}</strong><small>View {metric.label.toLowerCase()} <ArrowUpRight size={14} /></small></Link>)}</div>{!editor && <>
    <div className="ad-dashboard-columns"><section className="ad-panel ad-upcoming"><div className="ad-panel-heading"><div><span className="ad-eyebrow">Coming next</span><h2>Upcoming surprises</h2></div><Link href="/admin/orders?upcoming=upcoming">View all <ArrowUpRight size={15} /></Link></div>{data.upcoming.length ? <div className="ad-upcoming-list">{data.upcoming.map(order => <Link className="ad-upcoming-item" key={str(order, "id")} href={`/admin/orders/${str(order, "id")}`}><div className="ad-date-tile"><strong>{order.surprise_date ? String(order.surprise_date).slice(8, 10) : "—"}</strong><span>{order.surprise_date ? new Date(`${order.surprise_date}T12:00:00+05:30`).toLocaleDateString("en-LK", { month: "short", timeZone: "Asia/Colombo" }) : "Date"}</span></div><div><h3>{str(order, "package_name", "Surprise booking")}</h3><p>{str(order, "customer_name")} · {str(order, "surprise_time")}</p><small>{str(order, "surprise_location")}</small></div><Badge value={str(order, "order_status", str(order, "status", "new"))} /></Link>)}</div> : <Empty heading="No upcoming surprises" text="Scheduled bookings will appear here, sorted by date and time." />}</section>
    <section className="ad-panel"><div className="ad-panel-heading"><h2>Recent customers</h2><Link href="/admin/customers">View all <ArrowUpRight size={15} /></Link></div>{data.recentCustomers.length ? <div className="ad-customer-preview">{data.recentCustomers.map(customer => <Link key={str(customer, "id")} href={`/admin/customers/${str(customer, "id")}`}><span className="ad-avatar">{str(customer, "name", str(customer, "full_name", "C")).slice(0, 1)}</span><span><strong>{str(customer, "name", str(customer, "full_name"))}</strong><small>{str(customer, "phone")}</small></span><ArrowUpRight size={16} /></Link>)}</div> : <Empty heading="No customers yet" text="Customers are created from genuine bookings." />}</section></div>
    <section className="ad-panel"><div className="ad-panel-heading"><h2>Recent orders</h2><Link href="/admin/orders">Manage orders <ArrowUpRight size={15} /></Link></div>{data.recentOrders.length ? <div className="ad-table-wrap"><table className="ad-table"><thead><tr><th>Order / Customer</th><th>Package</th><th>Surprise date</th><th>Location</th><th>Amount</th><th>Status</th></tr></thead><tbody>{data.recentOrders.map(order => <tr key={str(order, "id")}><td data-label="Order / Customer"><Link href={`/admin/orders/${str(order, "id")}`}><strong>{str(order, "id").slice(0, 8)}</strong><span className="ad-cell-sub">{str(order, "customer_name")}</span></Link></td><td data-label="Package">{str(order, "package_name")}</td><td data-label="Surprise date">{date(order.surprise_date)}<span className="ad-cell-sub">{str(order, "surprise_time")}</span></td><td data-label="Location">{str(order, "surprise_location")}</td><td data-label="Amount">{money(order.total ?? order.total_amount, str(order, "currency", "LKR"))}</td><td data-label="Status"><Badge value={str(order, "order_status", str(order, "status", "new"))} /></td></tr>)}</tbody></table></div> : <Empty heading="No orders yet" text="Bookings submitted through the website will appear here." />}</section>
    {role === "super_admin" && <section className="ad-panel"><div className="ad-panel-heading"><h2>Recent activity</h2><Link href="/admin/activity">Full activity log <ArrowUpRight size={15} /></Link></div>{data.recentActivity.length ? <div className="ad-activity-preview">{data.recentActivity.map((item, i) => <div key={str(item, "id", String(i))}><span className="ad-activity-dot" /><p><strong>{str(item, "action").replaceAll("_", " ")}</strong> · {str(item, "entity_type")}<small>{date(item.created_at, true)}</small></p></div>)}</div> : <Empty heading="No activity yet" text="Administrative changes will be recorded here." />}</section>}
  </>}</>}</>;
}
