"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowDown, ArrowUp, Plus, Trash2, Upload, Save, Copy, Archive, LoaderCircle, Image as ImageIcon, ExternalLink } from "lucide-react";
import { api, Entity, labels, Loading, mutate, Notice, Row, rows, str, title, useResource, date } from "./shared";
import { CustomerDetail, OrderDetail } from "./operations";

type ImageValue = { image_path: string; alt_text: string; display_order: number };
function initial(entity: Entity): Row { return { active: true, featured: false, published: false, display_order: 0, ...(entity === "packages" ? { order_mode: "cart", price: "", collection_ids: [], items: [], images: [], video_orientation: "landscape" } : {}), ...(entity === "gallery" ? { media_type: "image" } : {}), ...(entity === "admins" ? { role: "editor" } : {}) }; }
export function AdminDetail({ entity, id }: { entity: Entity; id: string }) {
  const request = useResource<{ row: Row }>(`/api/admin/${entity}?id=${encodeURIComponent(id)}`);
  if (id === "new") return <RecordEditor key={`${entity}:new`} entity={entity} row={initial(entity)} />;
  if (request.loading) return <Loading />;
  if (request.error || !request.data?.row) return <><Link className="ad-back" href={`/admin/${entity}`}><ArrowLeft size={16} />Back to {labels[entity].toLowerCase()}</Link><Notice error={request.error || "This record could not be found."} /><button className="ad-button ad-button--secondary" onClick={request.refresh}>Try again</button></>;
  if (entity === "orders") return <OrderDetail row={request.data.row} />;
  if (entity === "customers") return <CustomerDetail row={request.data.row} />;
  if (entity === "media") return <MediaDetail row={request.data.row} />;
  return <RecordEditor key={`${entity}:${id}`} entity={entity} row={request.data.row} />;
}
export function ImageUploader({ value, onChange, folder, label = "Image" }: { value: string; onChange: (v: string) => void; folder: string; label?: string }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function upload(file?: File) { if (!file) return; setError(""); if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || !/\.(jpe?g|png|webp)$/i.test(file.name)) { setError("Choose a JPEG, PNG, or WebP image."); return; } if (file.size > 10 * 1024 * 1024) { setError("Maximum file size is 10 MB."); return; } setBusy(true); try { const form = new FormData(); form.set("file", file); form.set("folder", folder); const result = await api<{ url: string }>("/api/admin/media/upload", { method: "POST", body: form }); onChange(result.url); } catch (e) { setError(e instanceof Error ? e.message : "Upload failed. Please try again."); } finally { setBusy(false); } }
  return <div className="ad-image-field"><span className="ad-field-label">{label}</span><div className="ad-image-preview">{value ? <img src={value} alt={`${label} preview`} /> : <div><ImageIcon size={26} /><span>No image selected</span></div>}</div><div className="ad-image-actions"><label className={`ad-button ad-button--secondary ad-upload-label ${busy ? "is-disabled" : ""}`}>{busy ? <LoaderCircle className="ad-spin" size={15} /> : <Upload size={15} />}{busy ? "Uploading…" : value ? "Replace image" : "Upload image"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e => { void upload(e.target.files?.[0]); e.target.value = ""; }} /></label>{value && <button type="button" className="ad-text-button ad-danger" disabled={busy} onClick={() => onChange("")}>Remove</button>}</div><span className="ad-hint">JPEG, PNG, or WebP · Maximum 10 MB</span><Notice error={error} /></div>;
}
function RecordEditor({ entity, row }: { entity: Entity; row: Row }) {
  const router = useRouter(); const [values, setValues] = useState<Row>({ ...row }); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [confirm, setConfirm] = useState<"delete" | "archive" | null>(null); const isNew = !row.id;
  const collections = useResource<{ rows: Row[] }>("/api/admin/collections?pageSize=200"); const packages = useResource<{ rows: Row[] }>("/api/admin/packages?pageSize=200");
  function set(key: string, value: unknown) { setValues(v => ({ ...v, [key]: value })); setSuccess(""); }
  async function save(event: React.FormEvent) { event.preventDefault(); if (busy) return; setError(""); setSuccess(""); setBusy(true); try { const payload = { ...values }; delete payload.id; delete payload.created_at; delete payload.updated_at; delete payload.archived_at; if (entity === "packages") { payload.price = values.price === "" || values.price === undefined ? null : Number(values.price); payload.items = rows(values.items).map((item, i) => ({ label: str(item, "label", ""), display_order: i })); payload.images = rows(values.images).map((item, i) => ({ image_path: str(item, "image_path", ""), alt_text: str(item, "alt_text", ""), display_order: i })); } if (entity === "reviews") payload.rating = values.rating === "" || values.rating === undefined ? null : Number(values.rating); if (entity === "content") payload.value = Number(values.value || 0); payload.display_order = Number(values.display_order || 0); const result = await mutate(entity, "save", isNew ? undefined : str(row, "id"), payload); setSuccess("Changes saved."); if (isNew && result.row?.id) { router.replace(`/admin/${entity}/${result.row.id}`); router.refresh(); } } catch (e) { setError(e instanceof Error ? e.message : "Unable to save. Please try again."); } finally { setBusy(false); } }
  async function action(name: "delete" | "archive" | "duplicate") { if (busy) return; setBusy(true); setError(""); try { const result = await mutate(entity, name, str(row, "id")); if (name === "duplicate" && result.row?.id) router.push(`/admin/${entity}/${result.row.id}`); else router.push(`/admin/${entity}`); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to complete this action."); } finally { setBusy(false); setConfirm(null); } }
  const text = (key: string, label: string, options: { required?: boolean; maxLength?: number; type?: string; hint?: string; full?: boolean } = {}) => <label className={`ad-field ${options.full ? "ad-field--full" : ""}`} key={key}>{label}<input value={str(values, key, "")} onChange={e => set(key, e.target.value)} type={options.type || "text"} required={options.required} maxLength={options.maxLength || 300} {...(options.type === "number" ? { min: 0, step: key === "price" ? "0.01" : "1" } : {})} />{options.hint && <span className="ad-hint">{options.hint}</span>}</label>;
  const area = (key: string, label: string, required = false) => <label className="ad-field ad-field--full" key={key}>{label}<textarea value={str(values, key, "")} onChange={e => set(key, e.target.value)} rows={4} maxLength={5000} required={required} /></label>;
  const check = (key: string, label: string, help: string) => <label className="ad-check" key={key}><input type="checkbox" checked={Boolean(values[key])} onChange={e => set(key, e.target.checked)} /><span><strong>{label}</strong><small>{help}</small></span></label>;
  const sectionName = entity === "content" ? "statistic" : entity === "gallery" ? "gallery moment" : entity === "admins" ? "team member" : entity.slice(0, -1);
  return <><Link className="ad-back" href={`/admin/${entity}`}><ArrowLeft size={16} />Back to {labels[entity].toLowerCase()}</Link><div className="ad-page-heading"><div><span className="ad-eyebrow">{labels[entity]}</span><h1>{isNew ? `Add ${sectionName}` : `Edit ${sectionName}`}</h1><p>{isNew ? "Add genuine business information, then save to publish your changes." : "Changes update the public website according to the record’s visibility."}</p></div>{entity === "packages" && !isNew && <button className="ad-button ad-button--secondary" disabled={busy} onClick={() => void action("duplicate")}><Copy size={16} />Duplicate package</button>}</div>
    <form onSubmit={save} className="ad-editor"><div className="ad-editor-main"><section className="ad-panel ad-form-panel"><h2>{entity === "admins" ? "Team member details" : "Details"}</h2><div className="ad-form-grid">
    {entity === "packages" && <>{text("name", "Package name", { required: true, maxLength: 160 })}{text("slug", "URL slug", { required: true, maxLength: 160, hint: "Lowercase letters, numbers, and hyphens. For example: birthday-surprise" })}{text("badge", "Short card label", { maxLength: 80 })}<label className="ad-field">Booking type<select value={str(values, "order_mode", "cart")} onChange={e => set("order_mode", e.target.value)}><option value="cart">Fixed price package</option><option value="enquiry">Request quote</option><option value="cake">Custom cake</option></select></label>{text("price", "Price (LKR)", { type: "number", required: values.order_mode === "cart", hint: "The price applies to new orders. Existing order amounts stay unchanged." })}{text("price_note", "Price note", { maxLength: 160 })}{area("description", "Package description", true)}<div className="ad-field ad-field--full"><span className="ad-field-label">Collections</span>{collections.error ? <Notice error="Collections could not be loaded. Refresh before editing assignments." /> : collections.loading ? <span className="ad-hint">Loading collections…</span> : collections.data?.rows.length ? <div className="ad-collection-checks">{collections.data.rows.map(collection => { const id = str(collection, "id"); const selected = Array.isArray(values.collection_ids) ? values.collection_ids as string[] : []; return <label key={id}><input type="checkbox" checked={selected.includes(id)} onChange={e => set("collection_ids", e.target.checked ? [...selected, id] : selected.filter(v => v !== id))} />{str(collection, "name")}</label>; })}</div> : <span className="ad-hint">Create a collection first to organize this package.</span>}</div>{text("video_url", "Package video URL", { hint: "Use an existing public video URL or local asset path.", full: true })}<label className="ad-field">Video orientation<select value={str(values, "video_orientation", "landscape")} onChange={e => set("video_orientation", e.target.value)}><option value="landscape">Landscape</option><option value="portrait">Portrait</option></select></label></>}
    {entity === "collections" && <>{text("name", "Collection name", { required: true, maxLength: 160 })}{text("slug", "URL slug", { required: true, maxLength: 160, hint: "Lowercase letters, numbers, and hyphens." })}{area("short_description", "Short description")}</>}
    {entity === "gallery" && <>{text("title", "Title", { maxLength: 160 })}{area("caption", "Caption")}<label className="ad-field">Media type<select value={str(values, "media_type", "image")} onChange={e => set("media_type", e.target.value)}><option value="image">Image</option><option value="video">Video</option></select></label>{values.media_type === "video" && text("image_path", "Public video URL", { required: true, full: true, hint: "Use an existing hosted video URL or local asset path." })}</>}
    {entity === "reviews" && <>{text("customer_name", "Customer name", { required: true, maxLength: 160 })}<label className="ad-field">Rating<select value={str(values, "rating", "")} onChange={e => set("rating", e.target.value)}><option value="">No rating</option>{[1, 2, 3, 4, 5].map(n => <option key={n} value={n}>{n} star{n === 1 ? "" : "s"}</option>)}</select></label>{area("review", "Customer review", true)}<label className="ad-field ad-field--full">Related package<select value={str(values, "package_id", "")} onChange={e => set("package_id", e.target.value || null)}><option value="">No related package</option>{packages.data?.rows.map(p => <option key={str(p, "id")} value={str(p, "id")}>{str(p, "name")}</option>)}</select></label></>}
    {entity === "content" && <>{text("key", "Statistic key", { required: true, maxLength: 80, hint: "Use a supported business counter. Ratings are calculated from published reviews." })}{text("label", "Label", { required: true, maxLength: 160 })}{text("value", "Value", { required: true, type: "number" })}{text("suffix", "Suffix", { maxLength: 20, hint: "For example: +" })}</>}
    {entity === "admins" && <>{isNew && text("id", "Existing Supabase Auth user ID", { required: true, maxLength: 36, full: true, hint: "Invite the person through the secure provisioning flow first, then associate their verified Auth user ID." })}{text("display_name", "Display name", { required: true, maxLength: 160 })}{text("email", "Email", { required: true, type: "email", maxLength: 254 })}<label className="ad-field">Role<select value={str(values, "role", "editor")} onChange={e => set("role", e.target.value)}><option value="editor">Editor — website content</option><option value="admin">Admin — business operations</option><option value="super_admin">Super admin — full access</option></select></label></>}
    </div></section>
    {entity === "packages" && <><section className="ad-panel ad-form-panel"><div className="ad-panel-heading"><div><h2>What’s included</h2><p className="ad-hint">Add, remove, and reorder the items customers receive.</p></div><button className="ad-button ad-button--secondary" type="button" onClick={() => set("items", [...rows(values.items), { label: "", display_order: rows(values.items).length }])}><Plus size={16} />Add item</button></div><div className="ad-inclusion-list">{rows(values.items).map((item, i, all) => <div className="ad-inclusion" key={i}><span>{String(i + 1).padStart(2, "0")}</span><input aria-label={`Included item ${i + 1}`} required value={str(item, "label", "")} maxLength={200} onChange={e => set("items", all.map((v, j) => j === i ? { ...v, label: e.target.value } : v))} /><Reorder index={i} count={all.length} onMove={offset => { const next = [...all]; [next[i], next[i + offset]] = [next[i + offset], next[i]]; set("items", next); }} /><button type="button" className="ad-icon ad-danger" aria-label={`Remove included item ${i + 1}`} onClick={() => set("items", all.filter((_, j) => j !== i))}><Trash2 size={16} /></button></div>)}{!rows(values.items).length && <p className="ad-hint">No inclusions yet. Add the items included in this package.</p>}</div></section><section className="ad-panel ad-form-panel"><h2>Package images</h2><ImageUploader value={str(values, "main_image", "")} onChange={v => set("main_image", v)} folder="packages" label="Main image" /><div className="ad-panel-heading ad-extra-image-heading"><h3>Additional images</h3><button type="button" className="ad-button ad-button--secondary" onClick={() => set("images", [...rows(values.images), { image_path: "", alt_text: "", display_order: rows(values.images).length }])}><Plus size={16} />Add image</button></div><div className="ad-additional-images">{rows(values.images).map((image, i, all) => <div className="ad-additional-image" key={i}><ImageUploader value={str(image, "image_path", "")} folder="packages" label={`Additional image ${i + 1}`} onChange={v => set("images", all.map((item, j) => j === i ? { ...item, image_path: v } as ImageValue : item))} /><label className="ad-field">Image description<input maxLength={200} value={str(image, "alt_text", "")} onChange={e => set("images", all.map((item, j) => j === i ? { ...item, alt_text: e.target.value } : item))} /></label><div className="ad-image-actions"><Reorder index={i} count={all.length} onMove={offset => { const next = [...all]; [next[i], next[i + offset]] = [next[i + offset], next[i]]; set("images", next); }} /><button className="ad-text-button ad-danger" type="button" onClick={() => set("images", all.filter((_, j) => j !== i))}>Remove image</button></div></div>)}</div></section></>}
    {entity === "collections" && <section className="ad-panel ad-form-panel"><h2>Collection image</h2><ImageUploader value={str(values, "cover_image", "")} onChange={v => set("cover_image", v)} folder="collections" label="Cover image" /></section>}
    {entity === "gallery" && values.media_type !== "video" && <section className="ad-panel ad-form-panel"><h2>Gallery image</h2><ImageUploader value={str(values, "image_path", "")} onChange={v => set("image_path", v)} folder="gallery" /></section>}
    {entity === "reviews" && <section className="ad-panel ad-form-panel"><h2>Customer image</h2><ImageUploader value={str(values, "customer_image", "")} onChange={v => set("customer_image", v)} folder="reviews" label="Customer image" /></section>}
    </div><aside className="ad-editor-side"><section className="ad-panel ad-form-panel"><h2>{entity === "admins" ? "Access" : "Publishing"}</h2>{entity === "reviews" ? check("published", "Published", "Show this review on the website.") : check("active", entity === "admins" ? "Active team member" : "Active", entity === "admins" ? "Allow this team member to access the console." : "Show this record where it is used on the website.")}{!["admins", "content"].includes(entity) && check("featured", "Featured", "Include this record in featured website areas.")}{entity !== "admins" && text("display_order", "Display order", { type: "number", hint: "Smaller numbers appear first." })}<Notice error={error} success={success} /><button className="ad-button ad-save" type="submit" disabled={busy}>{busy ? <LoaderCircle className="ad-spin" size={17} /> : <Save size={17} />}{busy ? "Saving…" : "Save changes"}</button><Link className="ad-cancel" href={`/admin/${entity}`}>Cancel</Link></section>{!isNew && <section className="ad-panel ad-form-panel ad-danger-zone"><h3>Record actions</h3>{["packages", "collections", "gallery"].includes(entity) && <button type="button" className="ad-button ad-button--secondary" disabled={busy} onClick={() => setConfirm("archive")}><Archive size={16} />Archive</button>}<button type="button" className="ad-button ad-button--danger" disabled={busy} onClick={() => setConfirm("delete")}><Trash2 size={16} />{entity === "admins" ? "Remove access" : "Delete record"}</button>{confirm && <div className="ad-confirm" role="alert"><strong>{title(confirm)} this {sectionName}?</strong><p>{confirm === "archive" ? "It will be hidden from the website. Existing orders will remain intact." : "This cannot be undone. Records needed by existing orders may be protected from deletion."}</p><div><button type="button" className="ad-button ad-button--danger" disabled={busy} onClick={() => void action(confirm)}>Confirm {confirm}</button><button type="button" className="ad-text-button" onClick={() => setConfirm(null)}>Cancel</button></div></div>}</section>}{row.created_at ? <div className="ad-record-dates"><span>Created {date(row.created_at)}</span><span>Updated {date(row.updated_at, true)}</span></div> : null}</aside></form></>;
}
function Reorder({ index, count, onMove }: { index: number; count: number; onMove: (offset: number) => void }) { return <div className="ad-reorder"><button type="button" className="ad-icon" disabled={index === 0} onClick={() => onMove(-1)} aria-label="Move item up"><ArrowUp size={15} /></button><button type="button" className="ad-icon" disabled={index === count - 1} onClick={() => onMove(1)} aria-label="Move item down"><ArrowDown size={15} /></button></div>; }
function MediaDetail({ row }: { row: Row }) { const router = useRouter(); const [confirm, setConfirm] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const url = str(row, "url", str(row, "public_url", str(row, "path", ""))); async function remove() { setBusy(true); try { await mutate("media", "delete", str(row, "id")); router.push("/admin/media"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to delete this asset."); } finally { setBusy(false); } } return <><Link className="ad-back" href="/admin/media"><ArrowLeft size={16} />Back to media library</Link><div className="ad-page-heading"><div><h1>Media details</h1><p>{str(row, "path")}</p></div></div><section className="ad-panel ad-media-detail"><img src={url} alt={str(row, "path").split("/").at(-1)} /><dl className="ad-details"><div><dt>File type</dt><dd>{str(row, "mime_type")}</dd></div><div><dt>Size</dt><dd>{(Number(row.size || 0) / 1024 / 1024).toFixed(2)} MB</dd></div><div><dt>Uploaded</dt><dd>{date(row.created_at, true)}</dd></div><div><dt>Usage</dt><dd>{str(row, "usage", "Usage unavailable")}</dd></div></dl><div className="ad-image-actions"><a className="ad-button ad-button--secondary" href={url} target="_blank" rel="noopener noreferrer"><ExternalLink size={16} />Open image</a><button className="ad-button ad-button--danger" disabled={busy} onClick={() => setConfirm(true)}><Trash2 size={16} />Delete image</button></div><Notice error={error} />{confirm && <div className="ad-confirm" role="alert"><strong>Delete this uploaded image?</strong><p>Only unused media can be removed. This action cannot be undone.</p><div><button className="ad-button ad-button--danger" disabled={busy} onClick={() => void remove()}>Confirm deletion</button><button className="ad-text-button" onClick={() => setConfirm(false)}>Cancel</button></div></div>}</section></>; }
