"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Plus, ArrowUpRight, Filter, RefreshCw, Image as ImageIcon, Upload, LoaderCircle } from "lucide-react";
import { Badge, date, descriptions, Empty, Entity, labels, Loading, money, Notice, orderStatuses, Pagination, paymentStatuses, Row, SearchField, str, title, useResource, api } from "./shared";

type Listing = { rows: Row[]; count: number; page: number; pageSize: number };
function itemName(entity: Entity, row: Row) { if (entity === "reviews") return str(row, "customer_name"); if (entity === "gallery") return str(row, "title", "Gallery moment"); if (entity === "content") return str(row, "label"); if (entity === "media") return str(row, "path").split("/").at(-1) || "Image"; return str(row, "name", str(row, "display_name", str(row, "full_name"))); }
const editable = new Set<Entity>(["packages", "collections", "gallery", "reviews", "content", "admins"]);
export function AdminList({ entity, initialFilters = {} }: { entity: Entity; initialFilters?: Record<string, string> }) {
  const [search, setSearch] = useState(""); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [filters, setFilters] = useState(initialFilters); const [uploadBusy, setUploadBusy] = useState(false); const [uploadError, setUploadError] = useState(""); const [uploadSuccess, setUploadSuccess] = useState("");
  useEffect(() => { const timer = setTimeout(() => { setQuery(search); setPage(1); }, 300); return () => clearTimeout(timer); }, [search]);
  const params = new URLSearchParams({ q: query, page: String(page), ...filters }); const listing = useResource<Listing>(`/api/admin/${entity}?${params}`); const lookups = useResource<Listing>(`/api/admin/${entity === "orders" ? "packages" : "collections"}?pageSize=200`);
  function filter(name: string, value: string) { setFilters(v => ({ ...v, [name]: value })); setPage(1); }
  async function upload(files: FileList | null) { if (!files?.length || uploadBusy) return; setUploadBusy(true); setUploadError(""); setUploadSuccess(""); let uploaded = 0; try { for (const file of Array.from(files)) { if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || !/\.(jpe?g|png|webp)$/i.test(file.name)) throw new Error(`${file.name}: choose a JPEG, PNG, or WebP image.`); if (file.size > 10 * 1024 * 1024) throw new Error(`${file.name}: maximum file size is 10 MB.`); const form = new FormData(); form.set("file", file); form.set("folder", entity === "gallery" ? "gallery" : "media"); const result = await api<{ url: string; path: string }>("/api/admin/media/upload", { method: "POST", body: form }); if (entity === "gallery") await api("/api/admin/gallery", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "save", values: { image_path: result.url, media_type: "image", title: file.name.replace(/\.[^.]+$/, "").replaceAll("-", " "), caption: "", active: true, featured: false, display_order: 0 } }) }); uploaded++; } setUploadSuccess(`${uploaded} image${uploaded === 1 ? "" : "s"} uploaded.`); } catch (e) { setUploadError(`${uploaded ? `${uploaded} image(s) uploaded. ` : ""}${e instanceof Error ? e.message : "Unable to upload."}`); } finally { setUploadBusy(false); listing.refresh(); } }
  const visual = ["packages", "collections", "gallery", "media"].includes(entity); const count = listing.data?.count ?? 0;
  return <><div className="ad-page-heading"><div><span className="ad-eyebrow">{entity === "orders" || entity === "customers" ? "Business operations" : entity === "admins" || entity === "activity" ? "Workspace administration" : "Website management"}</span><h1>{labels[entity]}</h1><p>{descriptions[entity]}</p></div><div className="ad-heading-actions">{["gallery", "media"].includes(entity) && <label className={`ad-button ad-button--secondary ad-upload-label ${uploadBusy ? "is-disabled" : ""}`}>{uploadBusy ? <LoaderCircle className="ad-spin" size={16} /> : <Upload size={16} />}{uploadBusy ? "Uploading…" : "Upload images"}<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={uploadBusy} onChange={e => { void upload(e.target.files); e.target.value = ""; }} /></label>}{editable.has(entity) && <Link className="ad-button" href={`/admin/${entity}/new`}><Plus size={17} />{entity === "content" ? "Add statistic" : entity === "admins" ? "Add team member" : `Add ${entity === "reviews" ? "review" : entity === "gallery" ? "moment" : entity.slice(0, -1)}`}</Link>}</div></div>
    <Notice error={uploadError || listing.error} success={uploadSuccess} /><section className="ad-panel ad-list-panel"><div className="ad-toolbar"><SearchField value={search} onChange={setSearch} placeholder={entity === "orders" ? "Search ID, name, phone, or recipient" : entity === "customers" ? "Search customer name or phone" : `Search ${labels[entity].toLowerCase()}`} /><div className="ad-toolbar-controls"><label className="ad-filter"><span className="ad-sr-only">Sort records</span><select value={filters.sort || ""} onChange={e => filter("sort", e.target.value)}><option value="">Default order</option><option value="newest">Newest first</option><option value="oldest">Oldest first</option>{visual && <option value="display_order">Display order</option>}</select></label><button className="ad-icon" onClick={listing.refresh} aria-label="Refresh records"><RefreshCw size={17} /></button></div></div>
    <div className="ad-filters"><Filter size={15} aria-hidden="true" />{entity === "orders" ? <><label><span>Status</span><select value={filters.status || ""} onChange={e => filter("status", e.target.value)}><option value="">All statuses</option>{orderStatuses.map(s => <option key={s} value={s}>{title(s)}</option>)}</select></label><label><span>Payment</span><select value={filters.payment_status || ""} onChange={e => filter("payment_status", e.target.value)}><option value="">Any payment</option>{paymentStatuses.map(s => <option key={s} value={s}>{title(s)}</option>)}</select></label><label><span>Package</span><select value={filters.package_id || ""} onChange={e => filter("package_id", e.target.value)}><option value="">All packages</option>{lookups.data?.rows.map(row => <option key={str(row, "id")} value={str(row, "id")}>{str(row, "name")}</option>)}</select></label><CollectionFilter value={filters.collection_id || ""} onChange={value => filter("collection_id", value)} /><label><span>From</span><input type="date" value={filters.from || ""} onChange={e => filter("from", e.target.value)} /></label><label><span>To</span><input type="date" value={filters.to || ""} onChange={e => filter("to", e.target.value)} /></label><label><span>Upcoming</span><select value={filters.upcoming || ""} onChange={e => filter("upcoming", e.target.value)}><option value="">All dates</option><option value="today">Today</option><option value="tomorrow">Tomorrow</option><option value="week">This week</option><option value="upcoming">Upcoming</option></select></label></> : entity === "reviews" ? <label><span>Visibility</span><select value={filters.status || ""} onChange={e => filter("status", e.target.value)}><option value="">All reviews</option><option value="published">Published</option><option value="pending">Pending review</option></select></label> : ["packages", "collections", "gallery", "content", "admins"].includes(entity) ? <label><span>Status</span><select value={filters.status || ""} onChange={e => filter("status", e.target.value)}><option value="">All records</option><option value="active">Active</option><option value="inactive">Inactive</option>{entity !== "admins" && entity !== "content" && <option value="archived">Archived</option>}</select></label> : <span>{count} record{count === 1 ? "" : "s"}</span>}{Object.values(filters).some(Boolean) && <button className="ad-text-button" onClick={() => { setFilters({}); setPage(1); }}>Clear filters</button>}</div>
    {listing.loading ? <Loading /> : listing.error ? <Empty heading="Records unavailable" text="Check your connection and refresh to try again." /> : !listing.data?.rows.length ? <Empty heading={`No ${labels[entity].toLowerCase()} found`} text={query || Object.values(filters).some(Boolean) ? "Try a different search or clear your filters." : entity === "orders" ? "Website bookings will appear here as they arrive." : "Add your first record to get started."} /> : visual ? <div className="ad-visual-grid">{listing.data.rows.map(row => { const source = str(row, entity === "packages" ? "main_image" : entity === "collections" ? "cover_image" : entity === "media" ? "url" : "image_path", entity === "media" ? str(row, "public_url", str(row, "path", "")) : ""); return <article className="ad-visual-card" key={str(row, "id")}><div className="ad-thumbnail">{source ? row.media_type === "video" ? <video src={source} controls preload="metadata" aria-label={itemName(entity, row)} /> : <img src={source} alt={itemName(entity, row)} loading="lazy" /> : <ImageIcon size={28} />}{row.featured === true && <span className="ad-featured">Featured</span>}</div><div className="ad-visual-body"><h3>{itemName(entity, row)}</h3>{entity === "packages" && <p>{money(row.price)}{row.badge ? <span> · {str(row, "badge")}</span> : null}</p>}{entity === "collections" && <p>{str(row, "short_description", "No description")}</p>}{entity === "gallery" && <p>{str(row, "caption", "No caption")}</p>}{entity === "media" && <p>{str(row, "mime_type")} · {Number(row.size || 0) >= 1024 ? `${(Number(row.size) / 1024 / 1024).toFixed(2)} MB` : `${Number(row.size || 0)} bytes`}<span className="ad-cell-sub">Uploaded {date(row.created_at)} · {str(row, "usage", "Usage unavailable")}</span></p>}<div className="ad-card-bottom">{entity !== "media" && <Badge value={row.archived_at ? "archived" : row.active === false ? "inactive" : "active"} />}<Link href={`/admin/${entity}/${str(row, "id")}`}>{entity === "media" ? "View details" : "Edit"}<ArrowUpRight size={15} /></Link></div></div></article>; })}</div> : <RecordTable entity={entity} records={listing.data.rows} />}
    <Pagination page={page} count={count} pageSize={listing.data?.pageSize || 20} onChange={setPage} /></section></>;
}
function CollectionFilter({ value, onChange }: { value: string; onChange: (value: string) => void }) { const { data } = useResource<Listing>("/api/admin/collections?pageSize=200"); return <label><span>Collection</span><select value={value} onChange={e => onChange(e.target.value)}><option value="">All collections</option>{data?.rows.map(row => <option key={str(row, "id")} value={str(row, "id")}>{str(row, "name")}</option>)}</select></label>; }
function RecordTable({ entity, records }: { entity: Entity; records: Row[] }) {
  const headings = entity === "orders" ? ["Order / Customer", "Contact", "Package", "Surprise date", "Location", "Amount", "Status"] : entity === "customers" ? ["Customer", "Phone", "Total orders", "Latest order", "Created"] : entity === "reviews" ? ["Customer", "Review", "Rating", "Visibility", "Display order"] : entity === "content" ? ["Statistic", "Value", "Status", "Display order"] : entity === "admins" ? ["Team member", "Email", "Role", "Status", "Created"] : ["Action", "Entity", "Record", "Team member", "Time"];
  return <div className="ad-table-wrap"><table className="ad-table"><thead><tr>{headings.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{records.map(row => { const href = `/admin/${entity}/${str(row, "id")}`; const primary = (text: string, secondary?: string) => <Link href={href}><strong>{text}</strong>{secondary && <span className="ad-cell-sub">{secondary}</span>}</Link>; const cells = entity === "orders" ? [primary(str(row, "id").slice(0, 8), str(row, "customer_name")), str(row, "customer_phone"), str(row, "package_name"), <span key="date">{date(row.surprise_date)}<span className="ad-cell-sub">{str(row, "surprise_time")}</span></span>, str(row, "surprise_location"), money(row.total ?? row.total_amount, str(row, "currency", "LKR")), <Badge key="status" value={str(row, "order_status", str(row, "status", "new"))} />] : entity === "customers" ? [primary(itemName(entity, row)), str(row, "phone"), str(row, "total_orders", "0"), date(row.latest_order ?? row.last_order_at), date(row.created_at)] : entity === "reviews" ? [primary(str(row, "customer_name")), <span className="ad-truncate" key="review">{str(row, "review")}</span>, row.rating ? `${row.rating} / 5` : "Unrated", <Badge key="published" value={row.published ? "published" : "pending"} />, str(row, "display_order", "0")] : entity === "content" ? [primary(str(row, "label"), str(row, "key")), `${str(row, "value", "0")}${str(row, "suffix", "")}`, <Badge key="active" value={row.active ? "active" : "inactive"} />, str(row, "display_order", "0")] : entity === "admins" ? [primary(str(row, "display_name")), str(row, "email"), title(str(row, "role")), <Badge key="active" value={row.active ? "active" : "inactive"} />, date(row.created_at)] : [title(str(row, "action")), str(row, "entity_type"), str(row, "entity_id").slice(0, 12), str(row, "admin_name", str(row, "admin_user_id").slice(0, 8)), date(row.created_at, true)]; return <tr key={str(row, "id")}>{cells.map((cell, i) => <td key={headings[i]} data-label={headings[i]}>{cell}</td>)}</tr>; })}</tbody></table></div>;
}
