"use client";

import { useState } from "react";
import { Save, LoaderCircle, UserRound, KeyRound } from "lucide-react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { api, Loading, mutate, Notice, Row, str, useResource } from "./shared";

const businessFields = [{ key: "phone", label: "Primary phone", type: "tel", hint: "The contact number shown on the website." }, { key: "whatsapp", label: "WhatsApp number", type: "tel", hint: "Include the country code, for example 9477…" }, { key: "instagram", label: "Instagram", type: "url" }, { key: "facebook", label: "Facebook", type: "url" }, { key: "tiktok", label: "TikTok", type: "url" }, { key: "google_review_url", label: "Google review link", type: "url" }];
export function BusinessSettings() { const request = useResource<{ rows: Row[] }>("/api/admin/settings?pageSize=200"); if (request.loading) return <Loading />; if (request.error) return <><Notice error={request.error} /><button className="ad-button" onClick={request.refresh}>Try again</button></>; return <SettingsForm key={JSON.stringify(request.data?.rows)} rows={request.data?.rows || []} />; }
function SettingsForm({ rows }: { rows: Row[] }) { const initial = Object.fromEntries(rows.map(row => [str(row, "key", ""), typeof row.value === "string" ? row.value : row.value === null ? "" : String(row.value ?? "")])); const [values, setValues] = useState<Record<string, string>>(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); setSuccess(""); try { for (const field of businessFields) if (values[field.key] !== initial[field.key]) await mutate("settings", "save", field.key, { key: field.key, value: values[field.key] || "" }); setSuccess("Business settings saved."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save settings."); } finally { setBusy(false); } } return <><div className="ad-page-heading"><div><span className="ad-eyebrow">Business information</span><h1>Business settings</h1><p>Keep your customer contact details and social links current.</p></div></div><form className="ad-panel ad-form-panel ad-settings-form" onSubmit={save}><h2>Contact & social links</h2><div className="ad-form-grid">{businessFields.map(field => <label className="ad-field" key={field.key}>{field.label}<input type={field.type} value={values[field.key] || ""} onChange={e => setValues(v => ({ ...v, [field.key]: e.target.value }))} maxLength={500} />{field.hint && <span className="ad-hint">{field.hint}</span>}</label>)}</div><Notice error={error} success={success} /><button className="ad-button" type="submit" disabled={busy}>{busy ? <LoaderCircle className="ad-spin" size={16} /> : <Save size={16} />}{busy ? "Saving…" : "Save settings"}</button></form></>; }
export function AdminProfile({ admin }: { admin: { display_name: string; email: string; role: string } }) { const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setSuccess(""); setBusy(true); const form = new FormData(event.currentTarget); const name = String(form.get("display_name") || "").trim(); const password = String(form.get("password") || ""); try { if (password && password.length < 12) throw new Error("Use a password with at least 12 characters."); if (password !== String(form.get("confirm") || "")) throw new Error("The new passwords do not match."); await api("/api/admin/profile", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ display_name: name }) }); if (password) { const client = getSupabaseBrowserClient(); if (!client) throw new Error("Unable to connect to authentication."); const { error } = await client.auth.updateUser({ password }); if (error) throw new Error(`Your name was saved, but the password could not be updated: ${error.message}`); } setSuccess("Profile saved."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update your profile."); } finally { setBusy(false); } } return <><div className="ad-page-heading"><div><span className="ad-eyebrow">Your workspace account</span><h1>Your profile</h1><p>Manage your display name and sign-in password.</p></div></div><form onSubmit={submit} className="ad-profile-form"><section className="ad-panel ad-form-panel"><h2><UserRound size={19} />Personal details</h2><div className="ad-form-grid"><label className="ad-field">Display name<input name="display_name" defaultValue={admin.display_name} maxLength={160} required /></label><label className="ad-field">Email<input type="email" value={admin.email} readOnly /></label><label className="ad-field">Role<input value={admin.role.replaceAll("_", " ")} readOnly /></label></div></section><section className="ad-panel ad-form-panel"><h2><KeyRound size={19} />Change password</h2><p className="ad-hint">Leave these fields empty to keep your current password.</p><div className="ad-form-grid"><label className="ad-field">New password<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} /></label><label className="ad-field">Confirm new password<input name="confirm" type="password" autoComplete="new-password" minLength={12} maxLength={128} /></label></div></section><Notice error={error} success={success} /><button className="ad-button" type="submit" disabled={busy}>{busy ? <LoaderCircle className="ad-spin" size={16} /> : <Save size={16} />}{busy ? "Saving…" : "Save profile"}</button></form></>; }
